package com.iptv.mktech.iptv;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.iptv.mktech.iptv.entiy.Account;
import com.iptv.mktech.iptv.entiy.Channel;
import com.iptv.mktech.iptv.entiy.Package;

import com.iptv.mktech.iptv.AccountDao;
import com.iptv.mktech.iptv.ChannelDao;
import com.iptv.mktech.iptv.PackageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig channelDaoConfig;
    private final DaoConfig packageDaoConfig;

    private final AccountDao accountDao;
    private final ChannelDao channelDao;
    private final PackageDao packageDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        channelDaoConfig = daoConfigMap.get(ChannelDao.class).clone();
        channelDaoConfig.initIdentityScope(type);

        packageDaoConfig = daoConfigMap.get(PackageDao.class).clone();
        packageDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        channelDao = new ChannelDao(channelDaoConfig, this);
        packageDao = new PackageDao(packageDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(Channel.class, channelDao);
        registerDao(Package.class, packageDao);
    }
    
    public void clear() {
        accountDaoConfig.clearIdentityScope();
        channelDaoConfig.clearIdentityScope();
        packageDaoConfig.clearIdentityScope();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public ChannelDao getChannelDao() {
        return channelDao;
    }

    public PackageDao getPackageDao() {
        return packageDao;
    }

}
